# Default values for vultr-csi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

vultrCSIRelease: "v0.17.1"

env:

controller:
  affinity: {}
  resources: {
     limits: {
        cpu: 100m
     }
  }
